# Solution for model FN
# Objective value = -1.1575625538211377e+05
wLIRA-LIRA 0
wLIRA-LIMF 0
wLIRA-LIBD 0
wLIRA-LIPZ 0
wLIRA-LIRQ 0
wLIRA-LICJ 0
wLIRA-LICA 0
wLIRA-LIEO 0
wLIRA-LIPX 0
wLIRA-LIPY 0
wLIRA-LIPQ 0
wLIRA-LIRN 0
wLIRA-LIBP 0
wLIRA-LIMJ 0
wLIRA-LICC 0
wLIMF-LIRA 0
wLIMF-LIMF 0
wLIMF-LIBD 1
wLIMF-LIPZ 0
wLIMF-LIRQ 0
wLIMF-LICJ 0
wLIMF-LICA 0
wLIMF-LIEO 0
wLIMF-LIPX 0
wLIMF-LIPY 0
wLIMF-LIPQ 0
wLIMF-LIRN 1
wLIMF-LIBP 0
wLIMF-LIMJ 0
wLIMF-LICC 0
wLIBD-LIRA 0
wLIBD-LIMF 1
wLIBD-LIBD 0
wLIBD-LIPZ 0
wLIBD-LIRQ 0
wLIBD-LICJ 0
wLIBD-LICA 0
wLIBD-LIEO 0
wLIBD-LIPX 0
wLIBD-LIPY 0
wLIBD-LIPQ 0
wLIBD-LIRN 0
wLIBD-LIBP 0
wLIBD-LIMJ 0
wLIBD-LICC 0
wLIPZ-LIRA 0
wLIPZ-LIMF 0
wLIPZ-LIBD 0
wLIPZ-LIPZ 0
wLIPZ-LIRQ 0
wLIPZ-LICJ 0
wLIPZ-LICA 0
wLIPZ-LIEO 0
wLIPZ-LIPX 0
wLIPZ-LIPY 0
wLIPZ-LIPQ 0
wLIPZ-LIRN 0
wLIPZ-LIBP 0
wLIPZ-LIMJ 0
wLIPZ-LICC 0
wLIRQ-LIRA 0
wLIRQ-LIMF 0
wLIRQ-LIBD 0
wLIRQ-LIPZ 0
wLIRQ-LIRQ 0
wLIRQ-LICJ 0
wLIRQ-LICA 6
wLIRQ-LIEO 0
wLIRQ-LIPX 0
wLIRQ-LIPY 0
wLIRQ-LIPQ 0
wLIRQ-LIRN 0
wLIRQ-LIBP 0
wLIRQ-LIMJ 0
wLIRQ-LICC 0
wLICJ-LIRA 0
wLICJ-LIMF 0
wLICJ-LIBD 0
wLICJ-LIPZ 0
wLICJ-LIRQ 0
wLICJ-LICJ 0
wLICJ-LICA 0
wLICJ-LIEO 0
wLICJ-LIPX 0
wLICJ-LIPY 0
wLICJ-LIPQ 0
wLICJ-LIRN 0
wLICJ-LIBP 0
wLICJ-LIMJ 0
wLICJ-LICC 0
wLICA-LIRA 0
wLICA-LIMF 0
wLICA-LIBD 0
wLICA-LIPZ 0
wLICA-LIRQ 6
wLICA-LICJ 0
wLICA-LICA 0
wLICA-LIEO 0
wLICA-LIPX 4
wLICA-LIPY 0
wLICA-LIPQ 0
wLICA-LIRN 0
wLICA-LIBP 0
wLICA-LIMJ 4
wLICA-LICC 0
wLIEO-LIRA 0
wLIEO-LIMF 0
wLIEO-LIBD 0
wLIEO-LIPZ 0
wLIEO-LIRQ 0
wLIEO-LICJ 0
wLIEO-LICA 0
wLIEO-LIEO 0
wLIEO-LIPX 0
wLIEO-LIPY 4
wLIEO-LIPQ 12
wLIEO-LIRN 0
wLIEO-LIBP 8
wLIEO-LIMJ 0
wLIEO-LICC 0
wLIPX-LIRA 0
wLIPX-LIMF 0
wLIPX-LIBD 0
wLIPX-LIPZ 0
wLIPX-LIRQ 0
wLIPX-LICJ 0
wLIPX-LICA 3
wLIPX-LIEO 1
wLIPX-LIPX 0
wLIPX-LIPY 0
wLIPX-LIPQ 0
wLIPX-LIRN 0
wLIPX-LIBP 0
wLIPX-LIMJ 0
wLIPX-LICC 7
wLIPY-LIRA 0
wLIPY-LIMF 0
wLIPY-LIBD 0
wLIPY-LIPZ 0
wLIPY-LIRQ 0
wLIPY-LICJ 0
wLIPY-LICA 0
wLIPY-LIEO 4
wLIPY-LIPX 0
wLIPY-LIPY 0
wLIPY-LIPQ 0
wLIPY-LIRN 0
wLIPY-LIBP 0
wLIPY-LIMJ 0
wLIPY-LICC 6
wLIPQ-LIRA 0
wLIPQ-LIMF 0
wLIPQ-LIBD 0
wLIPQ-LIPZ 0
wLIPQ-LIRQ 0
wLIPQ-LICJ 0
wLIPQ-LICA 0
wLIPQ-LIEO 12
wLIPQ-LIPX 0
wLIPQ-LIPY 0
wLIPQ-LIPQ 0
wLIPQ-LIRN 0
wLIPQ-LIBP 0
wLIPQ-LIMJ 0
wLIPQ-LICC 0
wLIRN-LIRA 0
wLIRN-LIMF 1
wLIRN-LIBD 0
wLIRN-LIPZ 0
wLIRN-LIRQ 0
wLIRN-LICJ 0
wLIRN-LICA 0
wLIRN-LIEO 0
wLIRN-LIPX 0
wLIRN-LIPY 0
wLIRN-LIPQ 0
wLIRN-LIRN 0
wLIRN-LIBP 0
wLIRN-LIMJ 5
wLIRN-LICC 0
wLIBP-LIRA 0
wLIBP-LIMF 0
wLIBP-LIBD 0
wLIBP-LIPZ 0
wLIBP-LIRQ 0
wLIBP-LICJ 0
wLIBP-LICA 0
wLIBP-LIEO 43
wLIBP-LIPX 0
wLIBP-LIPY 0
wLIBP-LIPQ 0
wLIBP-LIRN 0
wLIBP-LIBP 0
wLIBP-LIMJ 2
wLIBP-LICC 0
wLIMJ-LIRA 0
wLIMJ-LIMF 0
wLIMJ-LIBD 0
wLIMJ-LIPZ 0
wLIMJ-LIRQ 0
wLIMJ-LICJ 0
wLIMJ-LICA 5
wLIMJ-LIEO 0
wLIMJ-LIPX 0
wLIMJ-LIPY 0
wLIMJ-LIPQ 0
wLIMJ-LIRN 5
wLIMJ-LIBP 1
wLIMJ-LIMJ 0
wLIMJ-LICC 0
wLICC-LIRA 0
wLICC-LIMF 0
wLICC-LIBD 0
wLICC-LIPZ 0
wLICC-LIRQ 0
wLICC-LICJ 0
wLICC-LICA 0
wLICC-LIEO 0
wLICC-LIPX 7
wLICC-LIPY 6
wLICC-LIPQ 0
wLICC-LIRN 0
wLICC-LIBP 0
wLICC-LIMJ 0
wLICC-LICC 0
xLIRA-LIRA 0
xLIRA-LIMF 110
xLIRA-LIBD 215
xLIRA-LIPZ 288
xLIRA-LIRQ 318
xLIRA-LICJ 180
xLIRA-LICA 150
xLIRA-LIEO 120
xLIRA-LIPX 277
xLIRA-LIPY 206
xLIRA-LIPQ 204
xLIRA-LIRN 354
xLIRA-LIBP 207
xLIRA-LIMJ 205
xLIRA-LICC 203
xLIMF-LIRA 110
xLIMF-LIMF 0
xLIMF-LIBD 0
xLIMF-LIPZ 108
xLIMF-LIRQ 108
xLIMF-LICJ 0
xLIMF-LICA 0
xLIMF-LIEO 0
xLIMF-LIPX 108
xLIMF-LIPY 56
xLIMF-LIPQ 56
xLIMF-LIRN 0
xLIMF-LIBP 0
xLIMF-LIMJ 106
xLIMF-LICC 0
xLIBD-LIRA 215
xLIBD-LIMF 0
xLIBD-LIBD 0
xLIBD-LIPZ 176
xLIBD-LIRQ 168
xLIBD-LICJ 119
xLIBD-LICA 108
xLIBD-LIEO 0
xLIBD-LIPX 120
xLIBD-LIPY 120
xLIBD-LIPQ 120
xLIBD-LIRN 216
xLIBD-LIBP 108
xLIBD-LIMJ 120
xLIBD-LICC 120
xLIPZ-LIRA 288
xLIPZ-LIMF 108
xLIPZ-LIBD 176
xLIPZ-LIPZ 0
xLIPZ-LIRQ 288
xLIPZ-LICJ 120
xLIPZ-LICA 120
xLIPZ-LIEO 56
xLIPZ-LIPX 360
xLIPZ-LIPY 180
xLIPZ-LIPQ 287
xLIPZ-LIRN 240
xLIPZ-LIBP 156
xLIPZ-LIMJ 180
xLIPZ-LICC 120
xLIRQ-LIRA 318
xLIRQ-LIMF 108
xLIRQ-LIBD 168
xLIRQ-LIPZ 288
xLIRQ-LIRQ 0
xLIRQ-LICJ 0
xLIRQ-LICA 0
xLIRQ-LIEO 92
xLIRQ-LIPX 288
xLIRQ-LIPY 180
xLIRQ-LIPQ 200
xLIRQ-LIRN 260
xLIRQ-LIBP 144
xLIRQ-LIMJ 216
xLIRQ-LICC 0
xLICJ-LIRA 180
xLICJ-LIMF 0
xLICJ-LIBD 119
xLICJ-LIPZ 120
xLICJ-LIRQ 0
xLICJ-LICJ 0
xLICJ-LICA 72
xLICJ-LIEO 56
xLICJ-LIPX 120
xLICJ-LIPY 0
xLICJ-LIPQ 0
xLICJ-LIRN 179
xLICJ-LIBP 56
xLICJ-LIMJ 0
xLICJ-LICC 144
xLICA-LIRA 150
xLICA-LIMF 0
xLICA-LIBD 108
xLICA-LIPZ 120
xLICA-LIRQ 0
xLICA-LICJ 72
xLICA-LICA 0
xLICA-LIEO 0
xLICA-LIPX 0
xLICA-LIPY 56
xLICA-LIPQ 0
xLICA-LIRN 144
xLICA-LIBP 56
xLICA-LIMJ 0
xLICA-LICC 108
xLIEO-LIRA 120
xLIEO-LIMF 0
xLIEO-LIBD 0
xLIEO-LIPZ 56
xLIEO-LIRQ 92
xLIEO-LICJ 56
xLIEO-LICA 0
xLIEO-LIEO 0
xLIEO-LIPX 56
xLIEO-LIPY 56
xLIEO-LIPQ 0
xLIEO-LIRN 92
xLIEO-LIBP 36
xLIEO-LIMJ 56
xLIEO-LICC 0
xLIPX-LIRA 277
xLIPX-LIMF 108
xLIPX-LIBD 120
xLIPX-LIPZ 360
xLIPX-LIRQ 288
xLIPX-LICJ 120
xLIPX-LICA 0
xLIPX-LIEO 56
xLIPX-LIPX 0
xLIPX-LIPY 144
xLIPX-LIPQ 216
xLIPX-LIRN 238
xLIPX-LIBP 120
xLIPX-LIMJ 216
xLIPX-LICC 120
xLIPY-LIRA 206
xLIPY-LIMF 56
xLIPY-LIBD 120
xLIPY-LIPZ 180
xLIPY-LIRQ 180
xLIPY-LICJ 0
xLIPY-LICA 56
xLIPY-LIEO 56
xLIPY-LIPX 144
xLIPY-LIPY 0
xLIPY-LIPQ 108
xLIPY-LIRN 144
xLIPY-LIBP 108
xLIPY-LIMJ 119
xLIPY-LICC 0
xLIPQ-LIRA 204
xLIPQ-LIMF 56
xLIPQ-LIBD 120
xLIPQ-LIPZ 287
xLIPQ-LIRQ 200
xLIPQ-LICJ 0
xLIPQ-LICA 0
xLIPQ-LIEO 0
xLIPQ-LIPX 216
xLIPQ-LIPY 108
xLIPQ-LIPQ 0
xLIPQ-LIRN 176
xLIPQ-LIBP 112
xLIPQ-LIMJ 120
xLIPQ-LICC 119
xLIRN-LIRA 354
xLIRN-LIMF 0
xLIRN-LIBD 216
xLIRN-LIPZ 240
xLIRN-LIRQ 260
xLIRN-LICJ 179
xLIRN-LICA 144
xLIRN-LIEO 92
xLIRN-LIPX 238
xLIRN-LIPY 144
xLIRN-LIPQ 176
xLIRN-LIRN 0
xLIRN-LIBP 180
xLIRN-LIMJ 120
xLIRN-LICC 176
xLIBP-LIRA 207
xLIBP-LIMF 0
xLIBP-LIBD 108
xLIBP-LIPZ 156
xLIBP-LIRQ 144
xLIBP-LICJ 56
xLIBP-LICA 56
xLIBP-LIEO 0
xLIBP-LIPX 120
xLIBP-LIPY 108
xLIBP-LIPQ 112
xLIBP-LIRN 180
xLIBP-LIBP 0
xLIBP-LIMJ 56
xLIBP-LICC 56
xLIMJ-LIRA 205
xLIMJ-LIMF 106
xLIMJ-LIBD 120
xLIMJ-LIPZ 180
xLIMJ-LIRQ 216
xLIMJ-LICJ 0
xLIMJ-LICA 0
xLIMJ-LIEO 56
xLIMJ-LIPX 216
xLIMJ-LIPY 119
xLIMJ-LIPQ 120
xLIMJ-LIRN 120
xLIMJ-LIBP 56
xLIMJ-LIMJ 0
xLIMJ-LICC 0
xLICC-LIRA 203
xLICC-LIMF 0
xLICC-LIBD 120
xLICC-LIPZ 120
xLICC-LIRQ 0
xLICC-LICJ 144
xLICC-LICA 108
xLICC-LIEO 0
xLICC-LIPX 120
xLICC-LIPY 0
xLICC-LIPQ 119
xLICC-LIRN 176
xLICC-LIBP 56
xLICC-LIMJ 0
xLICC-LICC 0
zLIRA-LIRA-RegionalTurboprop 0
zLIRA-LIMF-RegionalTurboprop 0
zLIRA-LIBD-RegionalTurboprop 6
zLIRA-LIPZ-RegionalTurboprop 8
zLIRA-LIRQ-RegionalTurboprop 9
zLIRA-LICJ-RegionalTurboprop 5
zLIRA-LICA-RegionalTurboprop 3
zLIRA-LIEO-RegionalTurboprop 5
zLIRA-LIPX-RegionalTurboprop 8
zLIRA-LIPY-RegionalTurboprop 6
zLIRA-LIPQ-RegionalTurboprop 6
zLIRA-LIRN-RegionalTurboprop 10
zLIRA-LIBP-RegionalTurboprop 6
zLIRA-LIMJ-RegionalTurboprop 6
zLIRA-LICC-RegionalTurboprop 6
zLIMF-LIRA-RegionalTurboprop 0
zLIMF-LIMF-RegionalTurboprop 0
zLIMF-LIBD-RegionalTurboprop 0
zLIMF-LIPZ-RegionalTurboprop 3
zLIMF-LIRQ-RegionalTurboprop 3
zLIMF-LICJ-RegionalTurboprop 0
zLIMF-LICA-RegionalTurboprop 0
zLIMF-LIEO-RegionalTurboprop 0
zLIMF-LIPX-RegionalTurboprop 3
zLIMF-LIPY-RegionalTurboprop 0
zLIMF-LIPQ-RegionalTurboprop 0
zLIMF-LIRN-RegionalTurboprop 0
zLIMF-LIBP-RegionalTurboprop 0
zLIMF-LIMJ-RegionalTurboprop 3
zLIMF-LICC-RegionalTurboprop 0
zLIBD-LIRA-RegionalTurboprop 6
zLIBD-LIMF-RegionalTurboprop 0
zLIBD-LIBD-RegionalTurboprop 0
zLIBD-LIPZ-RegionalTurboprop 0
zLIBD-LIRQ-RegionalTurboprop 0
zLIBD-LICJ-RegionalTurboprop 0
zLIBD-LICA-RegionalTurboprop 3
zLIBD-LIEO-RegionalTurboprop 0
zLIBD-LIPX-RegionalTurboprop 0
zLIBD-LIPY-RegionalTurboprop 0
zLIBD-LIPQ-RegionalTurboprop 0
zLIBD-LIRN-RegionalTurboprop 6
zLIBD-LIBP-RegionalTurboprop 3
zLIBD-LIMJ-RegionalTurboprop 0
zLIBD-LICC-RegionalTurboprop 0
zLIPZ-LIRA-RegionalTurboprop 8
zLIPZ-LIMF-RegionalTurboprop 3
zLIPZ-LIBD-RegionalTurboprop 0
zLIPZ-LIPZ-RegionalTurboprop 0
zLIPZ-LIRQ-RegionalTurboprop 8
zLIPZ-LICJ-RegionalTurboprop 0
zLIPZ-LICA-RegionalTurboprop 0
zLIPZ-LIEO-RegionalTurboprop 0
zLIPZ-LIPX-RegionalTurboprop 10
zLIPZ-LIPY-RegionalTurboprop 5
zLIPZ-LIPQ-RegionalTurboprop 8
zLIPZ-LIRN-RegionalTurboprop 0
zLIPZ-LIBP-RegionalTurboprop 1
zLIPZ-LIMJ-RegionalTurboprop 5
zLIPZ-LICC-RegionalTurboprop 0
zLIRQ-LIRA-RegionalTurboprop 9
zLIRQ-LIMF-RegionalTurboprop 3
zLIRQ-LIBD-RegionalTurboprop 0
zLIRQ-LIPZ-RegionalTurboprop 8
zLIRQ-LIRQ-RegionalTurboprop 0
zLIRQ-LICJ-RegionalTurboprop 0
zLIRQ-LICA-RegionalTurboprop 0
zLIRQ-LIEO-RegionalTurboprop 1
zLIRQ-LIPX-RegionalTurboprop 8
zLIRQ-LIPY-RegionalTurboprop 5
zLIRQ-LIPQ-RegionalTurboprop 4
zLIRQ-LIRN-RegionalTurboprop 1
zLIRQ-LIBP-RegionalTurboprop 4
zLIRQ-LIMJ-RegionalTurboprop 6
zLIRQ-LICC-RegionalTurboprop 0
zLICJ-LIRA-RegionalTurboprop 5
zLICJ-LIMF-RegionalTurboprop 0
zLICJ-LIBD-RegionalTurboprop 0
zLICJ-LIPZ-RegionalTurboprop 0
zLICJ-LIRQ-RegionalTurboprop 0
zLICJ-LICJ-RegionalTurboprop 0
zLICJ-LICA-RegionalTurboprop 2
zLICJ-LIEO-RegionalTurboprop 0
zLICJ-LIPX-RegionalTurboprop 0
zLICJ-LIPY-RegionalTurboprop 0
zLICJ-LIPQ-RegionalTurboprop 0
zLICJ-LIRN-RegionalTurboprop 5
zLICJ-LIBP-RegionalTurboprop 0
zLICJ-LIMJ-RegionalTurboprop 0
zLICJ-LICC-RegionalTurboprop 4
zLICA-LIRA-RegionalTurboprop 3
zLICA-LIMF-RegionalTurboprop 0
zLICA-LIBD-RegionalTurboprop 3
zLICA-LIPZ-RegionalTurboprop 0
zLICA-LIRQ-RegionalTurboprop 0
zLICA-LICJ-RegionalTurboprop 2
zLICA-LICA-RegionalTurboprop 0
zLICA-LIEO-RegionalTurboprop 0
zLICA-LIPX-RegionalTurboprop 0
zLICA-LIPY-RegionalTurboprop 0
zLICA-LIPQ-RegionalTurboprop 0
zLICA-LIRN-RegionalTurboprop 4
zLICA-LIBP-RegionalTurboprop 0
zLICA-LIMJ-RegionalTurboprop 0
zLICA-LICC-RegionalTurboprop 3
zLIEO-LIRA-RegionalTurboprop 4
zLIEO-LIMF-RegionalTurboprop 0
zLIEO-LIBD-RegionalTurboprop 0
zLIEO-LIPZ-RegionalTurboprop 0
zLIEO-LIRQ-RegionalTurboprop 1
zLIEO-LICJ-RegionalTurboprop 0
zLIEO-LICA-RegionalTurboprop 0
zLIEO-LIEO-RegionalTurboprop 0
zLIEO-LIPX-RegionalTurboprop 0
zLIEO-LIPY-RegionalTurboprop 0
zLIEO-LIPQ-RegionalTurboprop 0
zLIEO-LIRN-RegionalTurboprop 1
zLIEO-LIBP-RegionalTurboprop 1
zLIEO-LIMJ-RegionalTurboprop 0
zLIEO-LICC-RegionalTurboprop 0
zLIPX-LIRA-RegionalTurboprop 8
zLIPX-LIMF-RegionalTurboprop 3
zLIPX-LIBD-RegionalTurboprop 0
zLIPX-LIPZ-RegionalTurboprop 10
zLIPX-LIRQ-RegionalTurboprop 8
zLIPX-LICJ-RegionalTurboprop 0
zLIPX-LICA-RegionalTurboprop 0
zLIPX-LIEO-RegionalTurboprop 0
zLIPX-LIPX-RegionalTurboprop 0
zLIPX-LIPY-RegionalTurboprop 4
zLIPX-LIPQ-RegionalTurboprop 6
zLIPX-LIRN-RegionalTurboprop 0
zLIPX-LIBP-RegionalTurboprop 0
zLIPX-LIMJ-RegionalTurboprop 6
zLIPX-LICC-RegionalTurboprop 0
zLIPY-LIRA-RegionalTurboprop 6
zLIPY-LIMF-RegionalTurboprop 0
zLIPY-LIBD-RegionalTurboprop 0
zLIPY-LIPZ-RegionalTurboprop 5
zLIPY-LIRQ-RegionalTurboprop 5
zLIPY-LICJ-RegionalTurboprop 0
zLIPY-LICA-RegionalTurboprop 0
zLIPY-LIEO-RegionalTurboprop 0
zLIPY-LIPX-RegionalTurboprop 4
zLIPY-LIPY-RegionalTurboprop 0
zLIPY-LIPQ-RegionalTurboprop 3
zLIPY-LIRN-RegionalTurboprop 4
zLIPY-LIBP-RegionalTurboprop 3
zLIPY-LIMJ-RegionalTurboprop 0
zLIPY-LICC-RegionalTurboprop 0
zLIPQ-LIRA-RegionalTurboprop 6
zLIPQ-LIMF-RegionalTurboprop 0
zLIPQ-LIBD-RegionalTurboprop 0
zLIPQ-LIPZ-RegionalTurboprop 8
zLIPQ-LIRQ-RegionalTurboprop 4
zLIPQ-LICJ-RegionalTurboprop 0
zLIPQ-LICA-RegionalTurboprop 0
zLIPQ-LIEO-RegionalTurboprop 0
zLIPQ-LIPX-RegionalTurboprop 6
zLIPQ-LIPY-RegionalTurboprop 3
zLIPQ-LIPQ-RegionalTurboprop 0
zLIPQ-LIRN-RegionalTurboprop 0
zLIPQ-LIBP-RegionalTurboprop 0
zLIPQ-LIMJ-RegionalTurboprop 0
zLIPQ-LICC-RegionalTurboprop 0
zLIRN-LIRA-RegionalTurboprop 10
zLIRN-LIMF-RegionalTurboprop 0
zLIRN-LIBD-RegionalTurboprop 6
zLIRN-LIPZ-RegionalTurboprop 0
zLIRN-LIRQ-RegionalTurboprop 1
zLIRN-LICJ-RegionalTurboprop 5
zLIRN-LICA-RegionalTurboprop 4
zLIRN-LIEO-RegionalTurboprop 1
zLIRN-LIPX-RegionalTurboprop 0
zLIRN-LIPY-RegionalTurboprop 4
zLIRN-LIPQ-RegionalTurboprop 0
zLIRN-LIRN-RegionalTurboprop 0
zLIRN-LIBP-RegionalTurboprop 5
zLIRN-LIMJ-RegionalTurboprop 0
zLIRN-LICC-RegionalTurboprop 0
zLIBP-LIRA-RegionalTurboprop 7
zLIBP-LIMF-RegionalTurboprop 0
zLIBP-LIBD-RegionalTurboprop 3
zLIBP-LIPZ-RegionalTurboprop 1
zLIBP-LIRQ-RegionalTurboprop 4
zLIBP-LICJ-RegionalTurboprop 0
zLIBP-LICA-RegionalTurboprop 0
zLIBP-LIEO-RegionalTurboprop 0
zLIBP-LIPX-RegionalTurboprop 0
zLIBP-LIPY-RegionalTurboprop 3
zLIBP-LIPQ-RegionalTurboprop 0
zLIBP-LIRN-RegionalTurboprop 5
zLIBP-LIBP-RegionalTurboprop 0
zLIBP-LIMJ-RegionalTurboprop 0
zLIBP-LICC-RegionalTurboprop 0
zLIMJ-LIRA-RegionalTurboprop 6
zLIMJ-LIMF-RegionalTurboprop 3
zLIMJ-LIBD-RegionalTurboprop 0
zLIMJ-LIPZ-RegionalTurboprop 5
zLIMJ-LIRQ-RegionalTurboprop 6
zLIMJ-LICJ-RegionalTurboprop 0
zLIMJ-LICA-RegionalTurboprop 0
zLIMJ-LIEO-RegionalTurboprop 0
zLIMJ-LIPX-RegionalTurboprop 6
zLIMJ-LIPY-RegionalTurboprop 0
zLIMJ-LIPQ-RegionalTurboprop 0
zLIMJ-LIRN-RegionalTurboprop 0
zLIMJ-LIBP-RegionalTurboprop 0
zLIMJ-LIMJ-RegionalTurboprop 0
zLIMJ-LICC-RegionalTurboprop 0
zLICC-LIRA-RegionalTurboprop 6
zLICC-LIMF-RegionalTurboprop 0
zLICC-LIBD-RegionalTurboprop 0
zLICC-LIPZ-RegionalTurboprop 0
zLICC-LIRQ-RegionalTurboprop 0
zLICC-LICJ-RegionalTurboprop 4
zLICC-LICA-RegionalTurboprop 3
zLICC-LIEO-RegionalTurboprop 0
zLICC-LIPX-RegionalTurboprop 0
zLICC-LIPY-RegionalTurboprop 0
zLICC-LIPQ-RegionalTurboprop 0
zLICC-LIRN-RegionalTurboprop 0
zLICC-LIBP-RegionalTurboprop 0
zLICC-LIMJ-RegionalTurboprop 0
zLICC-LICC-RegionalTurboprop 0
zLIRA-LIRA-RegionalJet 0
zLIRA-LIMF-RegionalJet 2
zLIRA-LIBD-RegionalJet 0
zLIRA-LIPZ-RegionalJet 0
zLIRA-LIRQ-RegionalJet 0
zLIRA-LICJ-RegionalJet 0
zLIRA-LICA-RegionalJet 1
zLIRA-LIEO-RegionalJet 0
zLIRA-LIPX-RegionalJet 0
zLIRA-LIPY-RegionalJet 0
zLIRA-LIPQ-RegionalJet 0
zLIRA-LIRN-RegionalJet 0
zLIRA-LIBP-RegionalJet 0
zLIRA-LIMJ-RegionalJet 0
zLIRA-LICC-RegionalJet 0
zLIMF-LIRA-RegionalJet 2
zLIMF-LIMF-RegionalJet 0
zLIMF-LIBD-RegionalJet 0
zLIMF-LIPZ-RegionalJet 0
zLIMF-LIRQ-RegionalJet 0
zLIMF-LICJ-RegionalJet 0
zLIMF-LICA-RegionalJet 0
zLIMF-LIEO-RegionalJet 0
zLIMF-LIPX-RegionalJet 0
zLIMF-LIPY-RegionalJet 1
zLIMF-LIPQ-RegionalJet 1
zLIMF-LIRN-RegionalJet 0
zLIMF-LIBP-RegionalJet 0
zLIMF-LIMJ-RegionalJet 0
zLIMF-LICC-RegionalJet 0
zLIBD-LIRA-RegionalJet 0
zLIBD-LIMF-RegionalJet 0
zLIBD-LIBD-RegionalJet 0
zLIBD-LIPZ-RegionalJet 1
zLIBD-LIRQ-RegionalJet 3
zLIBD-LICJ-RegionalJet 0
zLIBD-LICA-RegionalJet 0
zLIBD-LIEO-RegionalJet 0
zLIBD-LIPX-RegionalJet 0
zLIBD-LIPY-RegionalJet 0
zLIBD-LIPQ-RegionalJet 0
zLIBD-LIRN-RegionalJet 0
zLIBD-LIBP-RegionalJet 0
zLIBD-LIMJ-RegionalJet 0
zLIBD-LICC-RegionalJet 0
zLIPZ-LIRA-RegionalJet 0
zLIPZ-LIMF-RegionalJet 0
zLIPZ-LIBD-RegionalJet 1
zLIPZ-LIPZ-RegionalJet 0
zLIPZ-LIRQ-RegionalJet 0
zLIPZ-LICJ-RegionalJet 0
zLIPZ-LICA-RegionalJet 0
zLIPZ-LIEO-RegionalJet 1
zLIPZ-LIPX-RegionalJet 0
zLIPZ-LIPY-RegionalJet 0
zLIPZ-LIPQ-RegionalJet 0
zLIPZ-LIRN-RegionalJet 0
zLIPZ-LIBP-RegionalJet 0
zLIPZ-LIMJ-RegionalJet 0
zLIPZ-LICC-RegionalJet 0
zLIRQ-LIRA-RegionalJet 0
zLIRQ-LIMF-RegionalJet 0
zLIRQ-LIBD-RegionalJet 3
zLIRQ-LIPZ-RegionalJet 0
zLIRQ-LIRQ-RegionalJet 0
zLIRQ-LICJ-RegionalJet 0
zLIRQ-LICA-RegionalJet 0
zLIRQ-LIEO-RegionalJet 1
zLIRQ-LIPX-RegionalJet 0
zLIRQ-LIPY-RegionalJet 0
zLIRQ-LIPQ-RegionalJet 1
zLIRQ-LIRN-RegionalJet 4
zLIRQ-LIBP-RegionalJet 0
zLIRQ-LIMJ-RegionalJet 0
zLIRQ-LICC-RegionalJet 0
zLICJ-LIRA-RegionalJet 0
zLICJ-LIMF-RegionalJet 0
zLICJ-LIBD-RegionalJet 0
zLICJ-LIPZ-RegionalJet 0
zLICJ-LIRQ-RegionalJet 0
zLICJ-LICJ-RegionalJet 0
zLICJ-LICA-RegionalJet 0
zLICJ-LIEO-RegionalJet 1
zLICJ-LIPX-RegionalJet 0
zLICJ-LIPY-RegionalJet 0
zLICJ-LIPQ-RegionalJet 0
zLICJ-LIRN-RegionalJet 0
zLICJ-LIBP-RegionalJet 1
zLICJ-LIMJ-RegionalJet 0
zLICJ-LICC-RegionalJet 0
zLICA-LIRA-RegionalJet 1
zLICA-LIMF-RegionalJet 0
zLICA-LIBD-RegionalJet 0
zLICA-LIPZ-RegionalJet 0
zLICA-LIRQ-RegionalJet 0
zLICA-LICJ-RegionalJet 0
zLICA-LICA-RegionalJet 0
zLICA-LIEO-RegionalJet 0
zLICA-LIPX-RegionalJet 0
zLICA-LIPY-RegionalJet 1
zLICA-LIPQ-RegionalJet 0
zLICA-LIRN-RegionalJet 0
zLICA-LIBP-RegionalJet 1
zLICA-LIMJ-RegionalJet 0
zLICA-LICC-RegionalJet 0
zLIEO-LIRA-RegionalJet 0
zLIEO-LIMF-RegionalJet 0
zLIEO-LIBD-RegionalJet 0
zLIEO-LIPZ-RegionalJet 1
zLIEO-LIRQ-RegionalJet 1
zLIEO-LICJ-RegionalJet 1
zLIEO-LICA-RegionalJet 0
zLIEO-LIEO-RegionalJet 0
zLIEO-LIPX-RegionalJet 1
zLIEO-LIPY-RegionalJet 1
zLIEO-LIPQ-RegionalJet 0
zLIEO-LIRN-RegionalJet 1
zLIEO-LIBP-RegionalJet 0
zLIEO-LIMJ-RegionalJet 1
zLIEO-LICC-RegionalJet 0
zLIPX-LIRA-RegionalJet 0
zLIPX-LIMF-RegionalJet 0
zLIPX-LIBD-RegionalJet 0
zLIPX-LIPZ-RegionalJet 0
zLIPX-LIRQ-RegionalJet 0
zLIPX-LICJ-RegionalJet 0
zLIPX-LICA-RegionalJet 0
zLIPX-LIEO-RegionalJet 1
zLIPX-LIPX-RegionalJet 0
zLIPX-LIPY-RegionalJet 0
zLIPX-LIPQ-RegionalJet 0
zLIPX-LIRN-RegionalJet 0
zLIPX-LIBP-RegionalJet 0
zLIPX-LIMJ-RegionalJet 0
zLIPX-LICC-RegionalJet 0
zLIPY-LIRA-RegionalJet 0
zLIPY-LIMF-RegionalJet 1
zLIPY-LIBD-RegionalJet 0
zLIPY-LIPZ-RegionalJet 0
zLIPY-LIRQ-RegionalJet 0
zLIPY-LICJ-RegionalJet 0
zLIPY-LICA-RegionalJet 1
zLIPY-LIEO-RegionalJet 1
zLIPY-LIPX-RegionalJet 0
zLIPY-LIPY-RegionalJet 0
zLIPY-LIPQ-RegionalJet 0
zLIPY-LIRN-RegionalJet 0
zLIPY-LIBP-RegionalJet 0
zLIPY-LIMJ-RegionalJet 0
zLIPY-LICC-RegionalJet 0
zLIPQ-LIRA-RegionalJet 0
zLIPQ-LIMF-RegionalJet 1
zLIPQ-LIBD-RegionalJet 0
zLIPQ-LIPZ-RegionalJet 0
zLIPQ-LIRQ-RegionalJet 1
zLIPQ-LICJ-RegionalJet 0
zLIPQ-LICA-RegionalJet 0
zLIPQ-LIEO-RegionalJet 0
zLIPQ-LIPX-RegionalJet 0
zLIPQ-LIPY-RegionalJet 0
zLIPQ-LIPQ-RegionalJet 0
zLIPQ-LIRN-RegionalJet 1
zLIPQ-LIBP-RegionalJet 2
zLIPQ-LIMJ-RegionalJet 0
zLIPQ-LICC-RegionalJet 0
zLIRN-LIRA-RegionalJet 0
zLIRN-LIMF-RegionalJet 0
zLIRN-LIBD-RegionalJet 0
zLIRN-LIPZ-RegionalJet 0
zLIRN-LIRQ-RegionalJet 4
zLIRN-LICJ-RegionalJet 0
zLIRN-LICA-RegionalJet 0
zLIRN-LIEO-RegionalJet 1
zLIRN-LIPX-RegionalJet 0
zLIRN-LIPY-RegionalJet 0
zLIRN-LIPQ-RegionalJet 1
zLIRN-LIRN-RegionalJet 0
zLIRN-LIBP-RegionalJet 0
zLIRN-LIMJ-RegionalJet 0
zLIRN-LICC-RegionalJet 1
zLIBP-LIRA-RegionalJet 0
zLIBP-LIMF-RegionalJet 0
zLIBP-LIBD-RegionalJet 0
zLIBP-LIPZ-RegionalJet 0
zLIBP-LIRQ-RegionalJet 0
zLIBP-LICJ-RegionalJet 1
zLIBP-LICA-RegionalJet 1
zLIBP-LIEO-RegionalJet 0
zLIBP-LIPX-RegionalJet 0
zLIBP-LIPY-RegionalJet 0
zLIBP-LIPQ-RegionalJet 2
zLIBP-LIRN-RegionalJet 0
zLIBP-LIBP-RegionalJet 0
zLIBP-LIMJ-RegionalJet 1
zLIBP-LICC-RegionalJet 1
zLIMJ-LIRA-RegionalJet 0
zLIMJ-LIMF-RegionalJet 0
zLIMJ-LIBD-RegionalJet 0
zLIMJ-LIPZ-RegionalJet 0
zLIMJ-LIRQ-RegionalJet 0
zLIMJ-LICJ-RegionalJet 0
zLIMJ-LICA-RegionalJet 0
zLIMJ-LIEO-RegionalJet 1
zLIMJ-LIPX-RegionalJet 0
zLIMJ-LIPY-RegionalJet 0
zLIMJ-LIPQ-RegionalJet 0
zLIMJ-LIRN-RegionalJet 0
zLIMJ-LIBP-RegionalJet 1
zLIMJ-LIMJ-RegionalJet 0
zLIMJ-LICC-RegionalJet 0
zLICC-LIRA-RegionalJet 0
zLICC-LIMF-RegionalJet 0
zLICC-LIBD-RegionalJet 0
zLICC-LIPZ-RegionalJet 0
zLICC-LIRQ-RegionalJet 0
zLICC-LICJ-RegionalJet 0
zLICC-LICA-RegionalJet 0
zLICC-LIEO-RegionalJet 0
zLICC-LIPX-RegionalJet 0
zLICC-LIPY-RegionalJet 0
zLICC-LIPQ-RegionalJet 0
zLICC-LIRN-RegionalJet 1
zLICC-LIBP-RegionalJet 1
zLICC-LIMJ-RegionalJet 0
zLICC-LICC-RegionalJet 0
zLIRA-LIRA-SingleAisleTwinEngineJet 0
zLIRA-LIMF-SingleAisleTwinEngineJet 0
zLIRA-LIBD-SingleAisleTwinEngineJet 0
zLIRA-LIPZ-SingleAisleTwinEngineJet 0
zLIRA-LIRQ-SingleAisleTwinEngineJet 0
zLIRA-LICJ-SingleAisleTwinEngineJet 0
zLIRA-LICA-SingleAisleTwinEngineJet 0
zLIRA-LIEO-SingleAisleTwinEngineJet 0
zLIRA-LIPX-SingleAisleTwinEngineJet 0
zLIRA-LIPY-SingleAisleTwinEngineJet 0
zLIRA-LIPQ-SingleAisleTwinEngineJet 0
zLIRA-LIRN-SingleAisleTwinEngineJet 0
zLIRA-LIBP-SingleAisleTwinEngineJet 0
zLIRA-LIMJ-SingleAisleTwinEngineJet 0
zLIRA-LICC-SingleAisleTwinEngineJet 0
zLIMF-LIRA-SingleAisleTwinEngineJet 0
zLIMF-LIMF-SingleAisleTwinEngineJet 0
zLIMF-LIBD-SingleAisleTwinEngineJet 0
zLIMF-LIPZ-SingleAisleTwinEngineJet 0
zLIMF-LIRQ-SingleAisleTwinEngineJet 0
zLIMF-LICJ-SingleAisleTwinEngineJet 0
zLIMF-LICA-SingleAisleTwinEngineJet 0
zLIMF-LIEO-SingleAisleTwinEngineJet 0
zLIMF-LIPX-SingleAisleTwinEngineJet 0
zLIMF-LIPY-SingleAisleTwinEngineJet 0
zLIMF-LIPQ-SingleAisleTwinEngineJet 0
zLIMF-LIRN-SingleAisleTwinEngineJet 0
zLIMF-LIBP-SingleAisleTwinEngineJet 0
zLIMF-LIMJ-SingleAisleTwinEngineJet 0
zLIMF-LICC-SingleAisleTwinEngineJet 0
zLIBD-LIRA-SingleAisleTwinEngineJet 0
zLIBD-LIMF-SingleAisleTwinEngineJet 0
zLIBD-LIBD-SingleAisleTwinEngineJet 0
zLIBD-LIPZ-SingleAisleTwinEngineJet 1
zLIBD-LIRQ-SingleAisleTwinEngineJet 0
zLIBD-LICJ-SingleAisleTwinEngineJet 1
zLIBD-LICA-SingleAisleTwinEngineJet 0
zLIBD-LIEO-SingleAisleTwinEngineJet 0
zLIBD-LIPX-SingleAisleTwinEngineJet 1
zLIBD-LIPY-SingleAisleTwinEngineJet 1
zLIBD-LIPQ-SingleAisleTwinEngineJet 1
zLIBD-LIRN-SingleAisleTwinEngineJet 0
zLIBD-LIBP-SingleAisleTwinEngineJet 0
zLIBD-LIMJ-SingleAisleTwinEngineJet 1
zLIBD-LICC-SingleAisleTwinEngineJet 1
zLIPZ-LIRA-SingleAisleTwinEngineJet 0
zLIPZ-LIMF-SingleAisleTwinEngineJet 0
zLIPZ-LIBD-SingleAisleTwinEngineJet 1
zLIPZ-LIPZ-SingleAisleTwinEngineJet 0
zLIPZ-LIRQ-SingleAisleTwinEngineJet 0
zLIPZ-LICJ-SingleAisleTwinEngineJet 1
zLIPZ-LICA-SingleAisleTwinEngineJet 1
zLIPZ-LIEO-SingleAisleTwinEngineJet 0
zLIPZ-LIPX-SingleAisleTwinEngineJet 0
zLIPZ-LIPY-SingleAisleTwinEngineJet 0
zLIPZ-LIPQ-SingleAisleTwinEngineJet 0
zLIPZ-LIRN-SingleAisleTwinEngineJet 2
zLIPZ-LIBP-SingleAisleTwinEngineJet 1
zLIPZ-LIMJ-SingleAisleTwinEngineJet 0
zLIPZ-LICC-SingleAisleTwinEngineJet 1
zLIRQ-LIRA-SingleAisleTwinEngineJet 0
zLIRQ-LIMF-SingleAisleTwinEngineJet 0
zLIRQ-LIBD-SingleAisleTwinEngineJet 0
zLIRQ-LIPZ-SingleAisleTwinEngineJet 0
zLIRQ-LIRQ-SingleAisleTwinEngineJet 0
zLIRQ-LICJ-SingleAisleTwinEngineJet 0
zLIRQ-LICA-SingleAisleTwinEngineJet 0
zLIRQ-LIEO-SingleAisleTwinEngineJet 0
zLIRQ-LIPX-SingleAisleTwinEngineJet 0
zLIRQ-LIPY-SingleAisleTwinEngineJet 0
zLIRQ-LIPQ-SingleAisleTwinEngineJet 0
zLIRQ-LIRN-SingleAisleTwinEngineJet 0
zLIRQ-LIBP-SingleAisleTwinEngineJet 0
zLIRQ-LIMJ-SingleAisleTwinEngineJet 0
zLIRQ-LICC-SingleAisleTwinEngineJet 0
zLICJ-LIRA-SingleAisleTwinEngineJet 0
zLICJ-LIMF-SingleAisleTwinEngineJet 0
zLICJ-LIBD-SingleAisleTwinEngineJet 1
zLICJ-LIPZ-SingleAisleTwinEngineJet 1
zLICJ-LIRQ-SingleAisleTwinEngineJet 0
zLICJ-LICJ-SingleAisleTwinEngineJet 0
zLICJ-LICA-SingleAisleTwinEngineJet 0
zLICJ-LIEO-SingleAisleTwinEngineJet 0
zLICJ-LIPX-SingleAisleTwinEngineJet 1
zLICJ-LIPY-SingleAisleTwinEngineJet 0
zLICJ-LIPQ-SingleAisleTwinEngineJet 0
zLICJ-LIRN-SingleAisleTwinEngineJet 0
zLICJ-LIBP-SingleAisleTwinEngineJet 0
zLICJ-LIMJ-SingleAisleTwinEngineJet 0
zLICJ-LICC-SingleAisleTwinEngineJet 0
zLICA-LIRA-SingleAisleTwinEngineJet 0
zLICA-LIMF-SingleAisleTwinEngineJet 0
zLICA-LIBD-SingleAisleTwinEngineJet 0
zLICA-LIPZ-SingleAisleTwinEngineJet 1
zLICA-LIRQ-SingleAisleTwinEngineJet 0
zLICA-LICJ-SingleAisleTwinEngineJet 0
zLICA-LICA-SingleAisleTwinEngineJet 0
zLICA-LIEO-SingleAisleTwinEngineJet 0
zLICA-LIPX-SingleAisleTwinEngineJet 0
zLICA-LIPY-SingleAisleTwinEngineJet 0
zLICA-LIPQ-SingleAisleTwinEngineJet 0
zLICA-LIRN-SingleAisleTwinEngineJet 0
zLICA-LIBP-SingleAisleTwinEngineJet 0
zLICA-LIMJ-SingleAisleTwinEngineJet 0
zLICA-LICC-SingleAisleTwinEngineJet 0
zLIEO-LIRA-SingleAisleTwinEngineJet 0
zLIEO-LIMF-SingleAisleTwinEngineJet 0
zLIEO-LIBD-SingleAisleTwinEngineJet 0
zLIEO-LIPZ-SingleAisleTwinEngineJet 0
zLIEO-LIRQ-SingleAisleTwinEngineJet 0
zLIEO-LICJ-SingleAisleTwinEngineJet 0
zLIEO-LICA-SingleAisleTwinEngineJet 0
zLIEO-LIEO-SingleAisleTwinEngineJet 0
zLIEO-LIPX-SingleAisleTwinEngineJet 0
zLIEO-LIPY-SingleAisleTwinEngineJet 0
zLIEO-LIPQ-SingleAisleTwinEngineJet 0
zLIEO-LIRN-SingleAisleTwinEngineJet 0
zLIEO-LIBP-SingleAisleTwinEngineJet 0
zLIEO-LIMJ-SingleAisleTwinEngineJet 0
zLIEO-LICC-SingleAisleTwinEngineJet 0
zLIPX-LIRA-SingleAisleTwinEngineJet 0
zLIPX-LIMF-SingleAisleTwinEngineJet 0
zLIPX-LIBD-SingleAisleTwinEngineJet 1
zLIPX-LIPZ-SingleAisleTwinEngineJet 0
zLIPX-LIRQ-SingleAisleTwinEngineJet 0
zLIPX-LICJ-SingleAisleTwinEngineJet 1
zLIPX-LICA-SingleAisleTwinEngineJet 0
zLIPX-LIEO-SingleAisleTwinEngineJet 0
zLIPX-LIPX-SingleAisleTwinEngineJet 0
zLIPX-LIPY-SingleAisleTwinEngineJet 0
zLIPX-LIPQ-SingleAisleTwinEngineJet 0
zLIPX-LIRN-SingleAisleTwinEngineJet 2
zLIPX-LIBP-SingleAisleTwinEngineJet 1
zLIPX-LIMJ-SingleAisleTwinEngineJet 0
zLIPX-LICC-SingleAisleTwinEngineJet 1
zLIPY-LIRA-SingleAisleTwinEngineJet 0
zLIPY-LIMF-SingleAisleTwinEngineJet 0
zLIPY-LIBD-SingleAisleTwinEngineJet 1
zLIPY-LIPZ-SingleAisleTwinEngineJet 0
zLIPY-LIRQ-SingleAisleTwinEngineJet 0
zLIPY-LICJ-SingleAisleTwinEngineJet 0
zLIPY-LICA-SingleAisleTwinEngineJet 0
zLIPY-LIEO-SingleAisleTwinEngineJet 0
zLIPY-LIPX-SingleAisleTwinEngineJet 0
zLIPY-LIPY-SingleAisleTwinEngineJet 0
zLIPY-LIPQ-SingleAisleTwinEngineJet 0
zLIPY-LIRN-SingleAisleTwinEngineJet 0
zLIPY-LIBP-SingleAisleTwinEngineJet 0
zLIPY-LIMJ-SingleAisleTwinEngineJet 1
zLIPY-LICC-SingleAisleTwinEngineJet 0
zLIPQ-LIRA-SingleAisleTwinEngineJet 0
zLIPQ-LIMF-SingleAisleTwinEngineJet 0
zLIPQ-LIBD-SingleAisleTwinEngineJet 1
zLIPQ-LIPZ-SingleAisleTwinEngineJet 0
zLIPQ-LIRQ-SingleAisleTwinEngineJet 0
zLIPQ-LICJ-SingleAisleTwinEngineJet 0
zLIPQ-LICA-SingleAisleTwinEngineJet 0
zLIPQ-LIEO-SingleAisleTwinEngineJet 0
zLIPQ-LIPX-SingleAisleTwinEngineJet 0
zLIPQ-LIPY-SingleAisleTwinEngineJet 0
zLIPQ-LIPQ-SingleAisleTwinEngineJet 0
zLIPQ-LIRN-SingleAisleTwinEngineJet 1
zLIPQ-LIBP-SingleAisleTwinEngineJet 0
zLIPQ-LIMJ-SingleAisleTwinEngineJet 1
zLIPQ-LICC-SingleAisleTwinEngineJet 1
zLIRN-LIRA-SingleAisleTwinEngineJet 0
zLIRN-LIMF-SingleAisleTwinEngineJet 0
zLIRN-LIBD-SingleAisleTwinEngineJet 0
zLIRN-LIPZ-SingleAisleTwinEngineJet 2
zLIRN-LIRQ-SingleAisleTwinEngineJet 0
zLIRN-LICJ-SingleAisleTwinEngineJet 0
zLIRN-LICA-SingleAisleTwinEngineJet 0
zLIRN-LIEO-SingleAisleTwinEngineJet 0
zLIRN-LIPX-SingleAisleTwinEngineJet 2
zLIRN-LIPY-SingleAisleTwinEngineJet 0
zLIRN-LIPQ-SingleAisleTwinEngineJet 1
zLIRN-LIRN-SingleAisleTwinEngineJet 0
zLIRN-LIBP-SingleAisleTwinEngineJet 0
zLIRN-LIMJ-SingleAisleTwinEngineJet 1
zLIRN-LICC-SingleAisleTwinEngineJet 1
zLIBP-LIRA-SingleAisleTwinEngineJet 0
zLIBP-LIMF-SingleAisleTwinEngineJet 0
zLIBP-LIBD-SingleAisleTwinEngineJet 0
zLIBP-LIPZ-SingleAisleTwinEngineJet 1
zLIBP-LIRQ-SingleAisleTwinEngineJet 0
zLIBP-LICJ-SingleAisleTwinEngineJet 0
zLIBP-LICA-SingleAisleTwinEngineJet 0
zLIBP-LIEO-SingleAisleTwinEngineJet 0
zLIBP-LIPX-SingleAisleTwinEngineJet 1
zLIBP-LIPY-SingleAisleTwinEngineJet 0
zLIBP-LIPQ-SingleAisleTwinEngineJet 0
zLIBP-LIRN-SingleAisleTwinEngineJet 0
zLIBP-LIBP-SingleAisleTwinEngineJet 0
zLIBP-LIMJ-SingleAisleTwinEngineJet 0
zLIBP-LICC-SingleAisleTwinEngineJet 0
zLIMJ-LIRA-SingleAisleTwinEngineJet 0
zLIMJ-LIMF-SingleAisleTwinEngineJet 0
zLIMJ-LIBD-SingleAisleTwinEngineJet 1
zLIMJ-LIPZ-SingleAisleTwinEngineJet 0
zLIMJ-LIRQ-SingleAisleTwinEngineJet 0
zLIMJ-LICJ-SingleAisleTwinEngineJet 0
zLIMJ-LICA-SingleAisleTwinEngineJet 0
zLIMJ-LIEO-SingleAisleTwinEngineJet 0
zLIMJ-LIPX-SingleAisleTwinEngineJet 0
zLIMJ-LIPY-SingleAisleTwinEngineJet 1
zLIMJ-LIPQ-SingleAisleTwinEngineJet 1
zLIMJ-LIRN-SingleAisleTwinEngineJet 1
zLIMJ-LIBP-SingleAisleTwinEngineJet 0
zLIMJ-LIMJ-SingleAisleTwinEngineJet 0
zLIMJ-LICC-SingleAisleTwinEngineJet 0
zLICC-LIRA-SingleAisleTwinEngineJet 0
zLICC-LIMF-SingleAisleTwinEngineJet 0
zLICC-LIBD-SingleAisleTwinEngineJet 1
zLICC-LIPZ-SingleAisleTwinEngineJet 1
zLICC-LIRQ-SingleAisleTwinEngineJet 0
zLICC-LICJ-SingleAisleTwinEngineJet 0
zLICC-LICA-SingleAisleTwinEngineJet 0
zLICC-LIEO-SingleAisleTwinEngineJet 0
zLICC-LIPX-SingleAisleTwinEngineJet 1
zLICC-LIPY-SingleAisleTwinEngineJet 0
zLICC-LIPQ-SingleAisleTwinEngineJet 1
zLICC-LIRN-SingleAisleTwinEngineJet 1
zLICC-LIBP-SingleAisleTwinEngineJet 0
zLICC-LIMJ-SingleAisleTwinEngineJet 0
zLICC-LICC-SingleAisleTwinEngineJet 0
ACRegionalTurboprop 6
ACRegionalJet 1
ACSingleAisleTwinEngineJet 1
